FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update && apt-get install --assume-yes wget
RUN apt-get install -y python3 \
                       python3-dev \
                       python3-pip \
    && apt-get clean \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY attackanalyze.sh /app
COPY getinfo.py /app
CMD ["/bin/sh", "./attackanalyze.sh"]