version: "3.5"
services:
  sf-processor:
    container_name: sf-processor
    image: yaofengchen/sf-processor:1.4
    privileged: true
    volumes:
      - socket-vol:/sock/
      - "./resources:/usr/local/sysflow/resources/elk"
    environment:
      DRIVER: socket
      INPUT_PATH: /sock/sysflow.sock
      CONFIG_PATH: /usr/local/sysflow/resources/elk/pipelines/pipeline.tee.elk.json
      EXPORTER_SOURCE: localhost
  sf-collector:
    container_name: sf-collector
    image: yaofengchen/sf-collector:1.4
    depends_on:
      - "sf-processor"
    privileged: true
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro 
      - /boot:/host/boot:ro 
      - /lib/modules:/host/lib/modules:ro 
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      - socket-vol:/sock/      
    environment:
      EXPORTER_ID: local
      NODE_IP: "127.0.0.1"
      FILTER: ${FILTER}
      INTERVAL: 300 
      SOCK_FILE: /sock/sysflow.sock
volumes:
  socket-vol:
networks:
  default:
    external: true
    name: docker-elk_elk

