run:
	docker-compose up -d

stop:
	docker-compose down

build:
#	-git clone https://github.com/sysflow-telemetry/sf-processor.git
#	cd sf-processor && git checkout master && make docker-build

clean:
	docker rmi -f yaofengchen/sf-collector:1.2
	docker rmi -f yaofengchen/sf-processor:1.2
