run:
	docker-compose -f docker-compose.no_elk.yml --env-file .env.no_elk up -d

stop:
	docker-compose -f docker-compose.no_elk.yml --env-file .env.no_elk down

build:
	docker pull yaofengchen/sf-collector:1.5
	docker pull yaofengchen/sf-processor:1.5

clean:
	docker rmi -f yaofengchen/sf-collector:1.5
	docker rmi -f yaofengchen/sf-processor:1.5
